### ISSUE TITLE
demo for controller code

### ISSUE THREAD

**Issue by Bhoft** [pceuropa/yii2-forms#1]
Hi I am interested in your form generation widget.
Is there any sample code of the controllers and views?

e.g. how to save the form, display a specific form form etc.?

**Comment by pceuropa** [comment]
Yes I have all code of controllers and views. I will add the code to readme in two hours

**Comment by pceuropa** [comment]
I posted the code on the [homepage of formBuilser](https://pceuropa.net/yii2-extensions/yii2-forms/manual)
When is [create action](https://pceuropa.net/yii2-extensions/yii2-forms/create), to save fhe form, have to click on button "Save Form". In update action is autosave. Any modification of form is save automatically.

**Comment by gambhirmakwana** [comment]
I Am Interesting form generation widget. Please Add All The Controller and All View Please share
![yii_base_errorexception](https://cloud.githubusercontent.com/assets/19174303/23691894/6d780dde-03f1-11e7-9caf-eb6b510d87c3.png)

**Comment by gambhirmakwana** [comment]
Above Error arriving display

**Comment by pceuropa** [comment]
Controller view return data $form_body (not index). If you need widget on index, change code controller index with view. 

Controller view:
`return $this->render('view', [ 'form_body' => $form->body] );`

By de way I propose use controller view will be easier.

**Comment by Bhoft** [comment]
Thanks for the controller code. 
I already figured out myself the actionCreate code by checking the model code (or at least similar to yours). 

What I miss is the "create" and "update" view e.g. how the config is generated for the FormBuilder when updating a form.

There are also some issues in the controller
`$form = new FormBuilder(['table' => $this->table]);`
should be 
`$form = new FormBuilder(['table_prefix' => $this->table_prefix]);`
because there isn't a table attribute in the FormBuilder.
(I changed also the variable name in the controller to table_prefix of course this also must be changed on the insert call.)

and in the FormBase class the tableShema function must be static
`public static function tableShema($array){`
as well as
`FormBase::onlyCorrectDataFields()`
`FormBase::getValidator()`

and `FormModel::findModelByUrl` and `FormModel::findModel`-
All functions called static but aren't set in the code.

**Comment by pceuropa** [comment]
Tnx for feedback. Sorry, in last version I changed everywhere **table_prefix** to **table**. This was after you have downloaded last version. FormBuilder is still waiting for a lot of changes. Please write which version you have. 
Tomorrow I plans to add FormBuilder as a module and next version.

**Comment by pceuropa** [comment]
I installed last 1.2.8 without problem/bug. 
`composer require pceuropa/yii2-forms 1.2.8`

**Comment by Bhoft** [comment]
I was referring to the version 1.2.7 as i have just seen that you have changed some codes 13 hours ago.
But I guess you still missed some changes :) as this still uses the table attribute https://pceuropa.net/yii2-extensions/yii2-forms/update/1

**Comment by pceuropa** [comment]
Tnx . My place have too version 1.2.8 .

**Comment by Bhoft** [comment]
In Form::radio select and checkbox the label isn't correctly set. Something like this is missing.
```
   if (isset($value['label'])){ 
       		$field->label($value['label']);
       }
```
Otherwise the fieldname (or the dynamicmodel attribute) is used as the label.

Another suggestion
I see that your formbuilder still have many issue in rendering (no preview in create, strange dropdown above tabs etc), missing input settings (e.g. no multi select etc.) so still lots of work to do.

Therefore wouldn't it be better to use some existing Formbuilder instead of generating own scripts?

Maybe you would find this FormBuilder interesting which uses existing JQuery libraries.
The Formbuilder returns only JSON Code for the input forms (so like yours body attribute).
https://github.com/meysampg/yii2-formbuilder

**Comment by pceuropa** [comment]
Tnx for suggestions. After start work i check all existing libraries, in all missing something. For this  I decided to do their own. meysampg/yii2-formbuilder is only formbuilder and base on strange UI. My application have formbuilder (jQuery), formRender (PHP Yii2 validate,) or formRender (JavaScript), emailResponder, createDatabase. Combination all this required something new. In The plan is to add modules (e.g other forms template) languages and much more

**Comment by gambhirmakwana** [comment]
Thanks Friends
Above Isues short out but how to update form it's not idea controller update method is create but view not create please help how to create update view 
controller update method is create code

```
public function actionUpdate($id){
		$model = FormModel::findModel($id);
		$form = new FormBuilder();
		$form->table = 'form_'.$id;
		//print_r($form);die;
		$r = Yii::$app->request;
		if ($r->isAjax) {
			\Yii::$app->response->format = 'json';
			switch (true) { 
				case $r->isGet: echo $model->body; break;
				case $r->post('form_data'): 
				$model->body = $r->post('form_data');
				return ['success' => $model->save()]; 
				case $r->post('add'): $form->addColumn($id, $r->post('add')); return ['success' => $form->success];
				case $r->post('delete'): $form->dropColumn($id, $r->post('delete'));  return ['success' => $form->success];
				case $r->post('change_name'):
				$field = $r->post('change_name');
				$form->renameColumn ( 'form_' . $id, $field['old'], $field['new'] );
				return ['success' => $form->success];   
				default: return ['success' => false];
			}
		} 
		else {
			return $this->render('update');
		}		
	}
```

**Comment by gambhirmakwana** [comment]
Update form  view like this functionality add my project  https://pceuropa.net/yii2-extensions/yii2-forms/update/1 

controller and update method is created but not idea how to create view

**Comment by Bhoft** [comment]
@gambhirmakwana  the view/update is just something like this:

```
        $config = ["get"=>true,"save"=>true,"autosave"=>true];
        echo \pceuropa\forms\FormBuilder::widget([
            'test_mode' => false,  
            'easy_mode' => true, 
            'config' => $config,
        ]);
```

**Comment by gambhirmakwana** [comment]
Thanks Friends Is working

**Comment by gambhirmakwana** [comment]
form is view and some detail are fill out and submit button click than form record is submit that record how to print

**Comment by gambhirmakwana** [comment]
https://pceuropa.net/yii2-extensions/yii2-forms/list/11  like these controller view

**Comment by gambhirmakwana** [comment]
yii2-form working it's good friends

**Comment by gambhirmakwana** [comment]
Please send code url preview form code view and controller method

**Comment by pceuropa** [comment]
I added run formBuilder as module, Module have all code url, [views](https://github.com/pceuropa/yii2-forms/tree/master/views/module) and [controller](https://github.com/pceuropa/yii2-forms/blob/master/controllers/ModuleController.php).
