### ISSUE TITLE
Events and Some Idea

### ISSUE THREAD

**Issue by masihfathi** [pceuropa/yii2-forms#3]
is it good idea to add events for each created form(JavaScript and Yii2 events)(such as, events can use for payment for forms)? and something else is it better to create model and model search for each created form ? (in the create and update table actions like gii but I think in this way permissions make problem). in this way we can add upload and add rules in the rule function or only just use anonymous class for model and model search class when needed in actions(in this way in the grid view can add search model).

**Comment by pceuropa** [comment]
Thank for your ideas. In last month a added many improvements. Additions events and model search for each form, it is to do, but need time.

**Comment by masihfathi** [comment]
thanks for your great work and ideas, i think it can be the best extension of Yii2 if it's completed and can make programming with Yii2 easier, faster and add features that a framework do the cms jobs easier.
