### ISSUE TITLE
Add drop form table when delete form

### ISSUE THREAD

**Issue by symssyms** [pceuropa/yii2-forms#7]
When delete form in table `from` table `form_` not drop.
Update actionDelete in ModuleController 

`public function actionDelete(int $id)`
 `{`
`       $form = FormModel::findModel($id);`
       `$form->delete();`
        `$dropTable = Yii::$app->getDb()->createCommand()->dropTable('form_'.$id)->execute();`
       ` if ($dropTable) {`
            `return $this->redirect(['user']);`
       ` }`
    `}`

**Comment by pceuropa** [comment]
@symssyms thank for suggestion. Added in 3.0.3
